variables:
  - group: Presidio-V2-CI
trigger: none
pr: none
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
  - task: Bash@3
    displayName: 'Package Wheel'
    inputs:
      targetType: 'inline'
      script: |
        set -eux  # fail on error
        pip install build
        python -m build --wheel
  - task: Bash@3
    displayName: 'Install twine'
    inputs:
      targetType: 'inline'
      script: |
        set -eux  # fail on error
        pip install twine
  - task: TwineAuthenticate@1
    displayName: 'Authenticate with PyPi'
    inputs:

      pythonUploadServiceConnection: Pypi-Presidio
  - task: Bash@3
    displayName: 'Upload Wheel to PyPi'
    inputs:
      targetType: 'inline'
      script: |
        set -eux  # fail on error
        twine upload -r presidio --verbose --config-file $(PYPIRC_PATH) --skip-existing dist/*
